defaultPlacement: end
enableVersioning: true
entryTypes:
  - 098569c8-f00d-4c16-af6c-547cdc5355ca # partials
handle: homepagina
maxAuthors: 1
name: homepagina
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58547a28-0e8c-418b-bdc6-e0211364b3df: # werkpakket
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
