defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8ca87005-2a06-4ea0-b48e-099d36045a60 # hero
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58547a28-0e8c-418b-bdc6-e0211364b3df: # werkpakket
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
