defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2993cc13-67e2-44da-9399-7695e242fd0b # paginationnumbers
handle: pagination
maxAuthors: 1
name: pagination
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58547a28-0e8c-418b-bdc6-e0211364b3df: # werkpakket
    enabledByDefault: true
    hasUrls: true
    template: partials\paginatie.twig
    uriFormat: 'pagination/{slug}'
type: channel
