defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7363b624-d162-4354-b877-e30497ba6398 # products
handle: productDetail
maxAuthors: 1
name: product_detail
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58547a28-0e8c-418b-bdc6-e0211364b3df: # werkpakket
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: products
type: single
