color: null
fieldLayouts:
  265bbc60-2ec9-498f-869d-e4f986bba2ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: filter
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1524fce0-b920-4a30-9863-17a407a1751c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # titelfilter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24705316-fc82-4cec-b2e4-ef3fe6118a35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce52172-ba47-4754-8aeb-db89241ea4e5 # labelfilter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f43a7eb2-2368-476c-a4db-fb563f1e04a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce52172-ba47-4754-8aeb-db89241ea4e5 # labelfilter
            handle: labelfilter2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcfe177f-a622-4155-899f-cd0f442fc55d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # titelfilter
            handle: titelfilter2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44f15733-6f23-476c-b6b4-62776b0e4d97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce52172-ba47-4754-8aeb-db89241ea4e5 # labelfilter
            handle: labelfilter4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dd9d9ee-001b-422d-9b00-5bd2f785a23d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce52172-ba47-4754-8aeb-db89241ea4e5 # labelfilter
            handle: labelfilter5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61e26563-425d-46d4-b5f7-d4bab41b7bb1
            userCondition: null
            warning: null
            width: 100
        name: filter
        uid: a191b464-18e5-4c81-97b3-cd83a34f28bb
        userCondition: null
handle: filter
hasTitleField: true
icon: ''
name: filter
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
