color: null
fieldLayouts:
  19fa1dc1-95dc-4daa-9fe6-f6653cf751cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: homepage
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c0ab1580-6c10-4ee5-aa7b-b135c3b2f794
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: dd4e242b-b1eb-48bb-abf5-82e3d392988a # heroDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 581d65b0-6ebd-4af7-a94d-ea21e6202d52
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 616c4d73-05db-42f3-b7b5-8e253693308a # heroTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09eb6c22-9109-420d-8ea4-0f972460f4e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 369c5ee2-6116-4715-a17c-22b3d77c08b9 # heroButton
            handle: herobutton
            includeInCards: false
            instructions: 'Bekijk producten'
            label: heroButton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b44c691-1fdd-432c-b814-20b9e1902e41
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba6823b7-8218-4a3c-8c5e-470c1785d47f
        userCondition: null
handle: hero
hasTitleField: true
icon: ''
name: hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
