color: null
fieldLayouts:
  6296e7bd-46b0-4fa4-be86-16991ffe08bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: loginform
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dad2c965-441b-45fa-9e09-f7e72460832c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35353d00-4cab-4a0e-a669-d61b256f8254 # logintitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba74b327-8e3f-4d05-8551-fa19beb14f58
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66b029c1-0cda-4a81-b820-89dc0396d81f # loginnaam
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b29e3f04-8d60-4932-a53d-180b56817170
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd903379-284c-434e-be64-06113d8ff5d4 # loginwachtwoord
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0be40500-c17a-4e15-8ab6-1dfa47a32983
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7535b6d-523c-4bcd-aea9-6d7fe5d0f55e # loginvergeten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4ab3d3d-6fd0-4f37-8380-c4df054e7308
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9411f8ff-0483-492d-9cc7-2307e15730dd # loginregistreren
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f8445ed-943b-4416-92a8-8679fe018d32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 091a0457-fea5-4a02-9005-55c31413fcf6 # loginbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b09be83-2eb4-4960-8a71-472cbd74b9d3
            userCondition: null
            warning: null
            width: 100
        name: loginform
        uid: 39944ab4-a1d9-43ef-9c54-9643f8f88bc0
        userCondition: null
handle: loginform
hasTitleField: true
icon: ''
name: loginform
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
