color: null
fieldLayouts:
  ddbd466a-6f0c-4afa-9a52-2e751b2dd2fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: navigationlinks
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 63a08351-d28b-4125-abc2-5e801751277c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b21380c9-70ac-4861-acbf-bce0ee9bf13a # link1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ffbd5b4-5a66-46eb-a8e4-3d828735aa38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1b23b535-50f0-404d-b93e-0fbf17fdcb64 # link2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a966049-ca77-42b1-9a24-85361fd153cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3de3078a-6a53-4ac6-8c62-2e1888c4b496 # link3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d191a4bd-617f-4c89-9660-9a7ca3499f59
            userCondition: null
            warning: null
            width: 100
        name: navigationLinks
        uid: 70733a79-1d15-40e1-8351-b698f64527a2
        userCondition: null
handle: navgationlinks
hasTitleField: true
icon: ''
name: navgationlinks
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
