color: null
fieldLayouts:
  73096d80-1b94-48e2-a41d-95c5f5e1adc6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: producten11
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 418eedd3-f0e3-47e7-ab66-8b49917d433b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dedf5a9-f7c5-46df-a5a0-36c78f056a1c # productenafbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68abb6d9-c5eb-4663-a6ad-3a3088ea9ce0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # titelfilter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8ebb3e-8aa3-43c0-8151-db099df07a45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f25f34a-2c4a-42be-b07b-b06902cd273a # producteninfo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebfea2d-097d-49ac-8289-0d82cede2560
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61030d7a-4412-43f6-9ffe-1fd3ada9c87f # productengewicht
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd438dd5-2221-44d2-90ed-737af1bb4a7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8058bf4-6f28-459d-9a8e-544d4a80c288 # productenbatterij
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f9e0115-03b8-4d09-8d44-4e1a60c93b45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5c7b65-2c3a-4b71-bad5-6a0324774bae # productengebruik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17c588ea-f83f-48d2-84a1-7f7fa2c6992b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38d8cbb1-9d0d-4620-8acd-5afcfcff7810 # productenprijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84fe1e75-34f4-4f68-9219-82ed681d3609
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ef1ad33-b74a-4c44-bdf8-9fa43d81fe81 # productenbekijkbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24c6135b-942f-42dc-aaa5-d443321896b7
            userCondition: null
            warning: null
            width: 100
        name: producten11
        uid: da04983d-d405-4c55-ba93-6db3c61c9db0
        userCondition: null
handle: producten11
hasTitleField: true
icon: ''
name: producten11
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
