color: null
fieldLayouts:
  e1fb55ad-acf9-4709-a73d-43e18d478867:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: producten4
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3a58da0-c526-4208-ba3f-08e7666ce89e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dedf5a9-f7c5-46df-a5a0-36c78f056a1c # productenafbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4de214f1-0d34-49fe-ac06-f1932ce25445
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # productentitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 321c71c7-d057-46f4-ac63-a82c62536fac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f25f34a-2c4a-42be-b07b-b06902cd273a # producteninfo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37fcb59d-4e53-40bf-95c5-033c5b950518
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61030d7a-4412-43f6-9ffe-1fd3ada9c87f # productengewicht
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27b5afa1-0531-4f6d-b1fd-22519002f70f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5c7b65-2c3a-4b71-bad5-6a0324774bae # productengebruik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b93af978-be44-4fd3-aba1-957b75711d2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38d8cbb1-9d0d-4620-8acd-5afcfcff7810 # productenprijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0646516e-af94-4c74-be34-88ce02ed7b97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ef1ad33-b74a-4c44-bdf8-9fa43d81fe81 # productenbekijkbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a507dd4f-0baf-4cd6-8cd4-d03b53fd7cad
            userCondition: null
            warning: null
            width: 100
        name: producten4
        uid: de76d07f-e03c-47e3-8a2c-8b08032111b4
        userCondition: null
handle: producten4
hasTitleField: true
icon: ''
name: producten4
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
