color: null
fieldLayouts:
  c0fe1915-98a3-46e9-9674-c8c476bce541:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: producten13
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1e666106-6280-4130-95c4-3dbb9add7334
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dedf5a9-f7c5-46df-a5a0-36c78f056a1c # productenafbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22ba654-d496-47e9-8080-264c4154274e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # titelfilter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 951530bb-c6ae-4aaf-9fa1-b83d54099776
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f25f34a-2c4a-42be-b07b-b06902cd273a # producteninfo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ce91477-8b68-47d1-bee1-901f3be2e778
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61030d7a-4412-43f6-9ffe-1fd3ada9c87f # productengewicht
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0269be2-2b12-480f-ad2b-024b94cf18b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8058bf4-6f28-459d-9a8e-544d4a80c288 # productenbatterij
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f869d07-bc43-4ad4-930e-1b7453680f9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5c7b65-2c3a-4b71-bad5-6a0324774bae # productengebruik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a73d0748-70dd-43bb-8c4b-81d978171fb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ef1ad33-b74a-4c44-bdf8-9fa43d81fe81 # productenbekijkbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 517d9e1a-a055-456c-9a08-2372206db017
            userCondition: null
            warning: null
            width: 100
        name: producten13
        uid: c69114ef-c7f6-40eb-99ee-bfb16606bae6
        userCondition: null
handle: producten13
hasTitleField: true
icon: ''
name: producten13
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
