color: null
fieldLayouts:
  648c64e1-bc2c-4546-8a22-50828828bcbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: productenpagina
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fdcf3769-ed8b-47ae-89c9-1a9069393b89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dedf5a9-f7c5-46df-a5a0-36c78f056a1c # productenafbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe531c26-e737-44cc-a552-4fbf10ac38ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # titelfilter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd3d42e-a7e0-44b8-a94b-755be7989b95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f25f34a-2c4a-42be-b07b-b06902cd273a # producteninfo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bec31a3-5d52-470a-b32e-06cc7aa689e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8058bf4-6f28-459d-9a8e-544d4a80c288 # productenbatterij
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf6f03c1-396c-4166-9c3c-9b9bf9bcd5f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5c7b65-2c3a-4b71-bad5-6a0324774bae # productengebruik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 631e6a64-c9d9-4e42-926b-7495118e81fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61030d7a-4412-43f6-9ffe-1fd3ada9c87f # productengewicht
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f580eb49-885b-4ac7-93cf-84b3d545920f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38d8cbb1-9d0d-4620-8acd-5afcfcff7810 # productenprijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8357ebd3-a26b-443f-9e9b-84a39156aab3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ef1ad33-b74a-4c44-bdf8-9fa43d81fe81 # productenbekijkbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f798336a-dd24-4662-a413-1586865b6400
            userCondition: null
            warning: null
            width: 100
        name: productenpagina
        uid: 3ef262b7-34f7-4842-af3c-405b3ff44972
        userCondition: null
handle: producten2
hasTitleField: true
icon: ''
name: producten2
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
