color: null
fieldLayouts:
  08f1367d-5dbd-4cfd-8b31-dfa0e54257a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0bb02628-379b-428b-aa4a-24649c4280c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ab6d4cf-34f7-4318-994a-ffd02b6d76d4 # imageproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8ca0614-123e-4149-9f3b-254d51012660
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1d0b93c-b243-4467-aad5-03b8465973c4 # titleproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4726dab-7311-48f7-be3b-98cc9d2ea616
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5cdeb9d3-6593-4c13-8610-dc70c406867e # batterylifeproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bcb37af-1561-4c7a-849a-35b71f83ccbf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d85749a2-e539-45d9-a08c-92d9c879780c # weightproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d51c0ab6-2c87-4c51-ad8c-775d57b53718
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41f1b00e-f6b4-49b2-acfa-675f82475060 # priceproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a27999df-a9fb-47d5-ba7e-a8b89e8ebeb0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e58860c8-016e-4624-b57e-7f9770a4cad1 # buttonimageproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 424eed9c-d3bb-43d9-9817-065bef5fb8a3
            userCondition: null
            warning: null
            width: 100
        name: productsthree
        uid: 815c7cc1-5f2a-40eb-8fe9-9975f910af48
        userCondition: null
handle: productsthree
hasTitleField: true
icon: ''
name: productsThree
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
