color: null
fieldLayouts:
  9892fd53-4419-4aca-81c3-2ab6fbbeda91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: productenpagina
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d921551-47d0-47c1-bbab-4ea9e3c008eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dedf5a9-f7c5-46df-a5a0-36c78f056a1c # productenafbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ab82eb1-72e9-46ca-b88f-9989fa024704
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d64669a-fd86-4cd1-ba7a-199bc71fc390 # productentitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34313ec1-2dc4-4af8-a45f-b05c926d74c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f25f34a-2c4a-42be-b07b-b06902cd273a # producteninfo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b7fb84b-4eef-403c-ba1b-89edd58dec8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5c7b65-2c3a-4b71-bad5-6a0324774bae # productengebruik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef50ec51-6cca-4646-b9f3-df4ee3a2e767
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61030d7a-4412-43f6-9ffe-1fd3ada9c87f # productengewicht
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e876c6-56b2-4511-b4f6-178e08c45d12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38d8cbb1-9d0d-4620-8acd-5afcfcff7810 # productenprijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e0a20ce-2ccf-4d9d-bdf9-84a524150968
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ef1ad33-b74a-4c44-bdf8-9fa43d81fe81 # productenbekijkbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ebe12ff-f681-4c04-bf28-60ee6556ce18
            userCondition: null
            warning: null
            width: 100
        name: productenpagina
        uid: 92f94df4-9c7f-475a-bc6b-8a4f0683b9de
        userCondition: null
handle: producten3
hasTitleField: true
icon: ''
name: producten3
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
