color: null
fieldLayouts:
  39e34b6e-c5df-4054-a513-4b42dc82f718:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: productone
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ce54939b-ad30-4712-b974-f7d25e6b05fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ab6d4cf-34f7-4318-994a-ffd02b6d76d4 # imageproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef5091e9-c946-41eb-a5bd-cd6e28722b78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1d0b93c-b243-4467-aad5-03b8465973c4 # titleproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d199ed8-1c57-4e45-a32c-2d6a5301fe03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5cdeb9d3-6593-4c13-8610-dc70c406867e # batterylifeproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45aef915-76f8-4be4-bba6-40b9c96c1d90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d85749a2-e539-45d9-a08c-92d9c879780c # weightproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a54bcf-f85c-411e-ad70-c1335114be7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41f1b00e-f6b4-49b2-acfa-675f82475060 # priceproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a06a1c37-de71-41e9-91f0-398312a86c54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e58860c8-016e-4624-b57e-7f9770a4cad1 # buttonproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 310b1ac3-970f-452f-bd41-b68ce4de783f
            userCondition: null
            warning: null
            width: 100
        name: product_one
        uid: 03757ece-68db-40cf-be45-d00349bfe995
        userCondition: null
handle: productsone
hasTitleField: true
icon: ''
name: productsone
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
