color: null
fieldLayouts:
  306e6a7f-cb02-4974-af50-e71a616ccfac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: relatedproduct
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ee11bde3-26a7-4ebb-a3fe-48efbe40cd06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ed38769-c394-4e43-b767-6f33dcb00d70 # title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f7cf82f-78b9-4056-9a9b-d4fa87f63958
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 845516fa-4644-4978-a11a-92b5accc1000 # price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18f10eb1-2e30-46b3-ab87-8505277c9169
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ab6d4cf-34f7-4318-994a-ffd02b6d76d4 # imageproduct
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43a646b7-7a35-4455-b2c0-f844808edd3e
            userCondition: null
            warning: null
            width: 100
        name: relatedProduct
        uid: e66d8946-a27c-4b84-83be-e58adf07e98a
        userCondition: null
handle: relatedproduct
hasTitleField: true
icon: ''
name: relatedProduct
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
