columnSuffix: null
handle: navigationlinks
instructions: null
name: navigationLinks
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - e02a49c9-d1fd-4785-ade6-e833773ec861 # footer
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
