columnSuffix: null
handle: urlproduct
instructions: null
name: urlproduct
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
